### ISSUE TITLE
Raise require nim version of checksums to 2.0?

### ISSUE THREAD

**Issue by PhilippMDoerner** [nim-lang/checksums#13]
Heyho, the nimble version of this package currently states: `requires "nim >= 1.6.12"`

Is this actually correct?

Mostly asking because the following does not compile:

```nim
import checksums/bcrypt
import std/sysrand

proc hash(pw: string): string =
  let salt = urandom(16)
  let hash = bcrypt(pw, generateSalt(12))
  return $hash

echo hash("lala")
```
```txt
/home/philipp/.nimble/pkgs2/checksums-0.1.0-5da023bd508223aa026ccd5fc3a75177f111226b/checksums/bcrypt.nim(464, 47) Error: expression has no address; maybe use 'unsafeAddr'
```

Which makes me assume it's not covered by the test suite, thus making me assume 1.6.12 may not actually be supported :smile:

**Comment by ringabout** [comment]
Make sense, it should be bumped to 2.0
