### ISSUE TITLE
can't compile md5 with nim-2.0.10

### ISSUE THREAD

**Issue by pfpulux** [nim-lang/checksums#21]
```
/usr/lib/nim/dist/checksums/src/checksums/md5.nim(234, 21) template/generic instantiation of `slice` from here
/usr/lib/nim/dist/checksums/src/checksums/md5.nim(121, 10) template/generic instantiation of `slice` from here
/usr/lib/nim/dist/checksums/src/checksums/md5.nim(116, 6) Error: type mismatch: got 'openArray[uint8]' for 'toOpenArrayByte($input, 0, len - 1)' but expected 'seq[uint8]'
```

Distro `void-linux`

Nim `Nim Compiler Version 2.0.10 [Linux: amd64]
Compiled at 2024-10-05
Copyright (c) 2006-2023 by Andreas Rumpf`

[This](https://github.com/void-linux/void-packages/blob/master/srcpkgs/nim/template) is the template to make the nim-package. It use the last tag from `checksums`.

**Comment by ringabout** [comment]
You are supposed to use the corresponding checksums commit for Nim 2.0.10 => https://github.com/nim-lang/Nim/blob/e941ee15be775fe3c46db1bed9b4f41c7dfb1334/koch.nim#L16

I will make the devel version work ith 2.0.10 later

**Comment by pfpulux** [comment]
The problem was in the distro-pkg, the dist packages is missing in the pkg. But a local copy was not up to date. See [PR](https://github.com/void-linux/void-packages/pull/52654)
